name: CI Pipeline

n:
  push:
    branches:
      - main
      - task-*
  pull_request:
    branches:
      - main
      - task-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check Python version
        run: python --version
