name: CI Pipeline for Financial News Analysis

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
      - task-*
  pull_request:
    branches:
      - main
      - task-*

# Define the job
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13" # Matches your .venv Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # Install linting tool

      # Lint Python code
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 notebooks/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 notebooks/ --count --max-complexity=10 --max-line-length=127 --statistics
